name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository klonen
        uses: actions/checkout@v3

      - name: 🧰 Node installieren
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      - name: 🔨 Projekt bauen
        run: npm run build

      - name: 🚀 Auf GitHub Pages veröffentlichen
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
